# Generated by Django 5.1.5 on 2025-01-27 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.IntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(99)])),
                ('end_point', models.IntegerField(validators=[django.core.validators.MinValueValidator(-99), django.core.validators.MaxValueValidator(100)])),
                ('name', models.CharField(max_length=255)),
                ('hex_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Color Codes',
                'verbose_name_plural': 'Colors Codes',
                'unique_together': {('name', 'hex_code')},
            },
        ),
    ]
