# Generated by Django 5.1.5 on 2025-01-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_codes', '0002_colorcodes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorcodes',
            name='temp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
