# Generated by Django 5.1.5 on 2025-01-28 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color_codes', '0003_colorcodes_temp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cloud', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cloud_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_color_weather', to='color_codes.colorcodes')),
                ('temp_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_color_weather', to='color_codes.colorcodes')),
                ('wind_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wind_color_weather', to='color_codes.colorcodes')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_country', to='weather.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_region', to='weather.region')),
            ],
            options={
                'verbose_name': 'City Weather',
                'verbose_name_plural': 'City Weathers',
            },
        ),
    ]
