# Generated by Django 5.1.5 on 2025-01-28 15:34

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    CityWeather = apps.get_model('weather', 'CityWeather')
    for row in CityWeather.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityweather',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_unique_uuids),
    ]
