# Generated by Django 5.1.5 on 2025-01-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_cityweather_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
    ]
